### ISSUE TITLE
Allagash >=0.4.1 requires python >=3.8

### ISSUE THREAD

**Issue by DManowitz** [apulverizer/allagash#62]
**Describe the bug**
Trying to use allagash v0.4.1 or higher on python <3.8 will not work.

**To Reproduce**
Attempt to import allagash on python 3.6 or 3.7.  The following error will result:
```
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\allagash\__init__.py", line 1, in <module>
    import importlib.metadata
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Expected behavior**
No error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.4.2 (should also happen in 0.4.1)
 - Python Version: 3.7

**Additional context**

**Comment by apulverizer** [comment]
This is fixed now with 0.4.3...sorry about that.
https://github.com/apulverizer/allagash/releases/tag/v0.4.3
